//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAFE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATMON
    {
        public int ID_HD { get; set; }
        public Nullable<int> ID_BAN { get; set; }
        public Nullable<int> ID_SP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> ID_TK { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
    
        public virtual BAN BAN { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
